/* BANCO DE DADOS - SAUDEMAIS HOSPITALAR */


CREATE DATABASE SAUDEMAIS_HOSPITALAR;


CREATE TABLE CLIENTE(
	IDPARCEIRO INT,
	PARCEIRO VARCHAR (30) NOT NULL, 
	PERFIL ENUM ('HAPVIDA','PRIVADO','PÚBLICO','CLÍNICA') 
	
);



CREATE TABLE EQUIPAMENTOS(
	IDEQUIPAMENTO INT, 
	MODELO VARCHAR (30),
	ID_PARCEIRO INT, 
	ID_MARCA INT

);



CREATE TABLE MARCAS(
	IDMARCA INT, 
	MARCA VARCHAR (30) 
);



CREATE TABLE PRODUTOS(
	IDPRODUTO INT,
	PRODUTO VARCHAR (30),  
	SETOR VARCHAR (30)
);



CREATE TABLE PRECO_PRODUTO(
	IDPRECO_PRODUTO INT, 
	PRECO FLOAT (10,2),
	ID_PRODUTO INT UNIQUE
);



CREATE TABLE ENDERECO(
	IDENDERECO INT,
	RUA VARCHAR (30) NOT NULL,
	CEP VARCHAR (30) NOT NULL, 
	UF CHAR (2) NOT NULL,
	CIDADE VARCHAR (30), 
	ID_PARCEIRO INT UNIQUE
);



CREATE TABLE FORNECEDOR(
	IDFORNECEDOR INT,
	FORNECEDOR VARCHAR(30), 
	ID_PRODUTO INT UNIQUE
);



CREATE TABLE PEDIDO(
	IDPEDIDO INT,
	STATUS_PEDIDO ENUM ('PENDENTE','PAGO','CANCELADO'),
	FORMA_PAGAMENTO ENUM ('PIX','BOLETO','CARTAO','TRANSFERENCIA'), 
	VALOR_TOTAL FLOAT (10,2) NOT NULL,
	DATA_PEDIDO DATETIME NOT NULL,
	ID_PAGAMENTO INT
);



CREATE TABLE ITEM_PEDIDO(
	IDITEM INT,
	QUANTIDADE INT NOT NULL,
	PRECO_UNITARIO FLOAT (10,2), 
	SUBTOTAL DECIMAL (10,2),
	ID_ESTOQUE INT
);



CREATE TABLE ESTOQUE(
	IDESTOQUE INT,
	QUANTIDADE_ESTOQUE INT NOT NULL, 
	ID_PRODUTO INT
);



CREATE TABLE PAGAMENTO(
	IDPAGAMENTO INT,
	DATA_PAGAMENTO DATETIME NOT NULL,
	VALOR_PAGO DECIMAL (10,2),
	FORMA_PAGAMENTO ENUM ('PIX','BOLETO','CARTAO','TRANSFERENCIA') NOT NULL,
	STATUS_PAGAMENTO ENUM ('PENDENTE','PAGO','CANCELADO') DEFAULT 'PENDENTE' 
);



CREATE TABLE MANUTENCAO_EQUIPAMENTO(
	IDMANUTENCAO INT,
	DATA_MANUTENCAO DATETIME NOT NULL,
	TIPO_MANUTENCAO ENUM ('PREVENTIVA','CORRETIVA','SEGURANCA ELETRICA') NOT NULL,
	DESCRICAO TEXT,
	CUSTO FLOAT (10,2),
	STATUS ENUM ('PENDENTE','CONCLUIDA') DEFAULT 'PENDENTE',
	ID_EQUIPAMENTO INT
);



/* CRIAÇÃO DE CONSTRAINTS - CHAVES PRIMÁRIAS */

ALTER TABLE CLIENTE 
ADD CONSTRAINT PK_IDPARCEIRO 
PRIMARY KEY AUTO_INCREMENT (IDPARCEIRO);


ALTER TABLE EQUIPAMENTOS
ADD CONSTRAINT PK_IDEQUIPAMENTO 
PRIMARY KEY AUTO_INCREMENT (IDEQUIPAMENTO);


ALTER TABLE MARCAS
ADD CONSTRAINT PK_IDMARCA
PRIMARY KEY AUTO_INCREMENT (IDMARCA);


ALTER TABLE PRODUTOS 
ADD CONSTRAINT PK_IDPRODUTO
PRIMARY KEY AUTO_INCREMENT (IDPRODUTO);


ALTER TABLE PRECO_PRODUTO
ADD CONSTRAINT PK_IDPRECOPRODUTO
PRIMARY KEY AUTO_INCREMENT (IDPRECO_PRODUTO);


ALTER TABLE ENDERECO 
ADD CONSTRAINT PK_IDENDERECO
PRIMARY KEY AUTO_INCREMENT (IDENDERECO);


ALTER TABLE FORNECEDOR 
ADD CONSTRAINT PK_IDFORNECEDOR
PRIMARY KEY AUTO_INCREMENT (IDFORNECEDOR);


ALTER TABLE PEDIDO 
ADD CONSTRAINT PK_IDPEDIDO
PRIMARY KEY AUTO_INCREMENT (IDPEDIDO);


ALTER TABLE ITEM_PEDIDO
ADD CONSTRAINT PK_IDITEM
PRIMARY KEY AUTO_INCREMENT (IDITEM);


ALTER TABLE ESTOQUE 
ADD CONSTRAINT PK_IDESTOQUE
PRIMARY KEY  AUTO_INCREMENT (IDESTOQUE);


ALTER TABLE PAGAMENTO 
ADD CONSTRAINT PK_IDPAGAMENTO
PRIMARY KEY AUTO_INCREMENT (IDPAGAMENTO);


ALTER TABLE MANUTENCAO_EQUIPAMENTO
ADD CONSTRAINT PK_IDMANUTENCAO
PRIMARY KEY AUTO_INCREMENT (IDMANUTENCAO);




/* CRIAÇÃO DE CONSTRAINTS - CHAVES ESTRANGEIRAS */

ALTER TABLE EQUIPAMENTOS
ADD CONSTRAINT FK_EQUIPAMENTOS_CLIENTE
FOREIGN KEY (ID_PARCEIRO) 
REFERENCES CLIENTE (IDPARCEIRO);

ALTER TABLE EQUIPAMENTOS 
ADD CONSTRAINT FK_EQUIPAMENTOS_MARCAS
FOREIGN KEY (ID_MARCA)
REFERENCES MARCAS (IDMARCA);

ALTER TABLE PRECO_PRODUTO
ADD CONSTRAINT FK_PRECOPRODUTO_PRODUTOS
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTOS (IDPRODUTO);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_CLIENTE
FOREIGN KEY (ID_PARCEIRO)
REFERENCES CLIENTE (IDPARCEIRO);

ALTER TABLE FORNECEDOR 
ADD CONSTRAINT FK_FORNECEDOR_PRODUTOS
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTOS (IDPRODUTO);

ALTER TABLE ITEM_PEDIDO
ADD CONSTRAINT FK_ITEMPEDIDO_ESTOQUE
FOREIGN KEY (ID_ESTOQUE)
REFERENCES ESTOQUE (IDESTOQUE);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_ESTOQUE_PRODUTOS
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTOS (IDPRODUTO);

ALTER TABLE MANUTENCAO_EQUIPAMENTO
ADD CONSTRAINT FK_MANUTENCAOEQUIPAMENTO_EQUIPAMENTOS
FOREIGN KEY (ID_EQUIPAMENTO)
REFERENCES EQUIPAMENTOS (IDEQUIPAMENTO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_PAGAMENTO
FOREIGN KEY (ID_PAGAMENTO)
REFERENCES PAGAMENTO (IDPAGAMENTO);




/* INSERT´S EM CADA TABELA */


/* INSERT´S NA TABELA CLIENTE */
INSERT INTO CLIENTE VALUES(NULL, 'HOSPITAL SANTA LUZIA', 'PRIVADO');
INSERT INTO CLIENTE VALUES(NULL, 'HOSPITAL DA RESTAURAÇÃO', 'PÚBLICO');
INSERT INTO CLIENTE VALUES(NULL, 'HAPVIDA SAUDE MAIS HOSPITALAR', 'HAPVIDA');
INSERT INTO CLIENTE VALUES(NULL, 'CLINICA SAUDE MAIS HOSPITALAR', 'CLÍNICA');
INSERT INTO CLIENTE VALUES(NULL, 'HOSPITAL GETULIO VARGAS', 'PRIVADO');

ALTER TABLE CLIENTE MODIFY 
IDPARCEIRO INT AUTO_INCREMENT;


/* INSERT´S NA TABELA ENDERECO */
INSERT INTO ENDERECO VALUES(NULL, 'RUA ANTONIO PINTO LAPA', '52081-521', 'PE', 'RECIFE', 1);
INSERT INTO ENDERECO VALUES(NULL, 'AVENIDA AGAMENON MAGALHAES', '52234-123', 'PE', 'RECIFE', 2);
INSERT INTO ENDERECO VALUES(NULL, 'ESTRADA DAS UBAIAS', '52060-082', 'PE', 'RECIFE', 3);
INSERT INTO ENDERECO VALUES(NULL, 'AVENIDA DOS PINHEIROS', '6870-872', 'PE', 'RECIFE', 5);
INSERT INTO ENDERECO VALUES(NULL, 'ESTRADA DOS PINTOS', '6578-231', 'PE', 'RECIFE', 4);

ALTER TABLE ENDERECO MODIFY 
IDENDERECO INT AUTO_INCREMENT;


/* INSERT´S NA TABELA MARCAS */
INSERT INTO MARCAS VALUES(NULL, 'GUERBET');
INSERT INTO MARCAS VALUES(NULL, 'BAYER');
INSERT INTO MARCAS VALUES(NULL, '1000MEDIC');
INSERT INTO MARCAS VALUES(NULL, 'ALKO DO BRASIL');
INSERT INTO MARCAS VALUES(NULL, 'LIEBEL');

ALTER TABLE MARCAS MODIFY 	
IDMARCA INT AUTO_INCREMENT;


/* INSERT´S NA TABELA EQUIPAMENTOS */
INSERT INTO EQUIPAMENTOS VALUES(NULL, 'ACCUTRON CT-D', 1, 1);
INSERT INTO EQUIPAMENTOS VALUES(NULL, 'INJETORA DE CONTRASTE SALIENT', 2, 2);
INSERT INTO EQUIPAMENTOS VALUES(NULL, 'ANGIOMAT ILLUMENA', 1, 1);
INSERT INTO EQUIPAMENTOS VALUES(NULL, 'SINOPOWER-D', 3, 3);
INSERT INTO EQUIPAMENTOS VALUES(NULL, 'OPTIVANTAGE DH', 1, 1);
INSERT INTO EQUIPAMENTOS VALUES(NULL, 'ANGIOMAT ILLUMENA SIEMENS', 5, 1);
INSERT INTO EQUIPAMENTOS VALUES(NULL, 'OPTIVANTAGE MULTI-USO', 4, 5);

ALTER TABLE EQUIPAMENTOS 
MODIFY IDEQUIPAMENTO INT AUTO_INCREMENT;



/* INSERT´S NA TABELA PRODUTOS */
INSERT INTO PRODUTOS VALUES(NULL, 'HENETIX', 'TOMOGRAFIA');
INSERT INTO PRODUTOS VALUES(NULL, 'DOTAREM', 'RESSONANCIA MAGNETICA');
INSERT INTO PRODUTOS VALUES(NULL, 'SERINGA DESCARTAVEL 200ML', 'TOMOGRAFIA');
INSERT INTO PRODUTOS VALUES(NULL, 'SERINGA DESCARTAVEL 150ML', 'HEMODINAMICA');
INSERT INTO PRODUTOS VALUES(NULL, 'OPTIRAY', 'HEMODINAMICA');

ALTER TABLE PRODUTOS 
MODIFY IDPRODUTO INT AUTO_INCREMENT;



/* INSERT´S NA TABELA ESTOQUE */
INSERT INTO ESTOQUE VALUES(NULL, 200, 1);
INSERT INTO ESTOQUE VALUES(NULL, 60, 2);
INSERT INTO ESTOQUE VALUES(NULL, 400, 3);
INSERT INTO ESTOQUE VALUES(NULL, 30, 4);
INSERT INTO ESTOQUE VALUES(NULL, 500, 5);

ALTER TABLE ESTOQUE 
MODIFY IDESTOQUE INT AUTO_INCREMENT;




/* INSERT´S NA TABELA FORNECEDOR */
INSERT INTO FORNECEDOR VALUES(NULL, 'GUERBET', 1);
INSERT INTO FORNECEDOR VALUES(NULL, 'GUERBET', 2);
INSERT INTO FORNECEDOR VALUES(NULL, 'ALKO DO BRASIL', 3);
INSERT INTO FORNECEDOR VALUES(NULL, 'ALKO DO BRASIL', 4);
INSERT INTO FORNECEDOR VALUES(NULL, 'GUERBET', 5);

ALTER TABLE FORNECEDOR 
MODIFY IDFORNECEDOR INT AUTO_INCREMENT;




/* INSERT´S NA TABELA PRECO_PRODUTO */
INSERT INTO PRECO_PRODUTO VALUES(NULL, 90.00, 1);
INSERT INTO PRECO_PRODUTO VALUES(NULL, 110.10, 2);
INSERT INTO PRECO_PRODUTO VALUES(NULL, 85.00, 3);
INSERT INTO PRECO_PRODUTO VALUES(NULL, 120.00, 4);
INSERT INTO PRECO_PRODUTO VALUES(NULL, 60.00, 5);

ALTER TABLE PRECO_PRODUTO 
MODIFY IDPRECO_PRODUTO INT AUTO_INCREMENT;



/* INSERT´S NA TABELA ITEM_PEDIDO */
INSERT INTO ITEM_PEDIDO VALUES(NULL, 60, 90.00, 60 * 90.00, 1); 
INSERT INTO ITEM_PEDIDO VALUES(NULL, 40, 110.10, 40 * 110.10, 2); 
INSERT INTO ITEM_PEDIDO VALUES(NULL, 150, 85.00, 150 * 85.00, 3); 
INSERT INTO ITEM_PEDIDO VALUES(NULL, 10, 120.00, 10 * 120.00, 4);
INSERT INTO ITEM_PEDIDO VALUES(NULL, 300, 60.00, 300 * 60.00, 5);

ALTER TABLE ITEM_PEDIDO 
MODIFY IDITEM INT AUTO_INCREMENT;




/* INSERT´S NA TABELA MANUTENCAO_EQUIPAMENTO */
INSERT INTO MANUTENCAO_EQUIPAMENTO VALUES(NULL, NOW(), 'PREVENTIVA', 'TROCA DA PLACA DA INJETORA', 13.000, 'PENDENTE', 1);
INSERT INTO MANUTENCAO_EQUIPAMENTO VALUES(NULL, NOW(), 'CORRETIVA', 'MENSAGEM DE ERRO 001', 5.000, 'PENDENTE', 2);
INSERT INTO MANUTENCAO_EQUIPAMENTO VALUES(NULL, NOW(), 'SEGURANCA ELETRICA', 'EQUIPAMENTO COM FALHA ALETRICA', 15.000, 'CONCLUIDA', 3);
INSERT INTO MANUTENCAO_EQUIPAMENTO VALUES(NULL, NOW(), 'PREVENTIVA', 'MANUTENÇÃO PROGRAMADA', 20.000, 'PENDENTE', 4);
INSERT INTO MANUTENCAO_EQUIPAMENTO VALUES(NULL, NOW(), 'PREVENTIVA', 'MANUTENÇÃO PROGRAMADA', 13.000, 'PENDENTE', 5);

ALTER TABLE MANUTENCAO_EQUIPAMENTO 
MODIFY IDMANUTENCAO INT AUTO_INCREMENT;




/* INSERT´S NA TABELA PAGAMENTO */
INSERT INTO PAGAMENTO VALUES(NULL, NOW(), 13.000, 'BOLETO', 'PENDENTE');
INSERT INTO PAGAMENTO VALUES(NULL, NOW(), 5.000, 'TRANSFERENCIA', 'PENDENTE');
INSERT INTO PAGAMENTO VALUES(NULL, NOW(), 15.000, 'PIX', 'PAGO');
INSERT INTO PAGAMENTO VALUES(NULL, NOW(), 20.000, 'BOLETO', 'PENDENTE');
INSERT INTO PAGAMENTO VALUES(NULL, NOW(), 13.000, 'BOLETO', 'PENDENTE');

ALTER TABLE PAGAMENTO 
MODIFY IDPAGAMENTO INT AUTO_INCREMENT;



/* INSERT´S NA TABELA PEDIDO */
INSERT INTO PEDIDO VALUES(NULL, 'PENDENTE', 'BOLETO', 13.000, NOW(), 1);
INSERT INTO PEDIDO VALUES(NULL, 'PENDENTE', 'TRANSFERENCIA', 5.000, NOW(), 2);
INSERT INTO PEDIDO VALUES(NULL, 'PENDENTE', 'PIX', 15.000, NOW(), 3);
INSERT INTO PEDIDO VALUES(NULL, 'PENDENTE', 'BOLETO', 20.000, NOW(), 4);
INSERT INTO PEDIDO VALUES(NULL, 'PENDENTE', 'BOLETO', 13.000, NOW(), 5);

ALTER TABLE PEDIDO 
MODIFY IDPEDIDO INT AUTO_INCREMENT;
